name: OpenTofu CI - env/common-nonprod

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - main
    paths:
    - env/common-nonprod/**
    - .github/workflows/env-common-nonprod-ci.yaml
    - .github/actions/tg-ci/**
    - Makefile

jobs:
  ci:
    permissions:
      contents: read
      security-events: write  # For `github/codeql-action/upload-sarif` to upload SARIF results
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v5

    - name: Run CI
      uses: ./.github/actions/tg-ci
      with:
        component-type: env
        component-name: common-nonprod
