name: OpenTofu CI - feature/networking

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    branches:
    - main
    paths:
    - feature/networking/**
    - .github/workflows/feature-networking-ci.yaml
    - .github/actions/tf-ci/**
    - Makefile

jobs:
  ci:
    permissions:
      contents: read
      security-events: write  # For `github/codeql-action/upload-sarif` to upload SARIF results
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v5

    - name: Run CI
      uses: ./.github/actions/tf-ci
      with:
        component-type: feature
        component-name: networking
